apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: lorranpimenta/projeto-database:1.0
      args:
        - "--ignore-db-dir=lost+found"
      imagePullPolicy: Always
      ports:
        - name: mysql
          containerPort: 3306
      volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql/
  volumes:
    - name: mysql-dados
      persistentVolumeClaim:
        claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: lorranpimenta/projeto-backend:1.0
          ports:
            - containerPort: 80